### ISSUE TITLE
HelloMutex.gm has -> instead of -->

### ISSUE THREAD

**Issue by J-S-Robinson** [ejaku/grgen#2]
In  grgen/engine-net-2/examples-api/HelloMutex/Mutex.gm the connect constraints are made using a -> operator instead of -->. 

As a result when I try to compile and run HelloMutex.exe I get:
```
Unhandled Exception: System.Exception:
Error while processing specification:
GrGen: [ERROR at Mutex.gm:8,9] no viable alternative at input 'Process'
```
and so on for each line with a ->.

Was an easy fix, but I figured you might want to know.

**Comment by ejaku** [comment]
Thx for the report, the fix is going to be contained in the upcoming 6.5 release.
